// (if frontend_framework != "none")
javascript_sources()

javascript_tests()

nodejs_project(
    name="web",
    package_json="package.json",
    dependencies=[
        "//packages/api-types:types",
    ]
)
